version: "3.8"
services:
  iipsrv:
    build: iipsrv
    volumes:
      - ./data:/data
    environment:
      - VERBOSITY=6
      - LOGFILE=/var/log/iipsrv.log
      - FILESYSTEM_PREFIX=/data/
      - MEMCACHED_SERVERS=memcached
    entrypoint: ["spawn-fcgi", "-n", "-f", "/iipsrv/iipsrv.fcgi", "-p", "9000"]

  memcached:
    image: memcached

  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www:/www
    ports:
      - "8094:80"

  solr:
    image: solr:8.5
    ports:
      - "8983:8983"
    volumes:
      - ./solr/install-plugin.sh:/docker-entrypoint-initdb.d/install-plugin.sh
      - ./solr/core:/opt/core-config
      - index-data:/var/solr/data
      - ./ocr:/ocr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - ocr
      - /opt/core-config

  iiif-search-api:
    build: iiif-search-api

volumes:
  index-data:
