version: "3.8"
services:
  iipsrv:
    image: atomotic/iipsrv:latest
    volumes:
      - ./data/images:/images
      - ./data/www:/www
      - ./data/manifests:/www/manifests
    environment:
      - LOGFILE=/dev/stderr
      - URI_MAP=iiif=>IIIF
      - VERBOSITY=1
      - FILESYSTEM_PREFIX=/images/
      - MEMCACHED_SERVERS=localhost
      - IIIF_VERSION=3
      - CORS=*
    ports:
      - ${IIPSRV_PORT}:80